### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by nihui** [MarsTechHAN/keras2ncnn#17] opened 2020-12-25 08:53 UTC
官方提供的 resnet50 h5
https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet50

https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels.h5
https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5

自己用 keras model.fit 训练，再 save 出来也是这个错误

然后 netron 打开是可以看到结构的

**Comment by MarsTechHAN** [comment] 2020-12-26 14:28
Rua Nihui!

I will update the loader with a more friendly error message when the structure descriptor is not found, but I am not able to reproduce the results.

![DE60436A47689C28EBD97D4C04F0B054](https://user-images.githubusercontent.com/10462805/103153147-59788000-47c9-11eb-892d-4b0caf91f57c.jpg)

**Comment by MarsTechHAN** [comment] 2021-01-22 12:03
I will close this issue since I am not able to reproduce this and no other issue has been raised.

**Closed by MarsTechHAN** 2021-01-22 12:03 UTC
Labels: Not able to reproduce

**Comment by nihui** [comment] 2021-01-23 01:49
谢谢
